# Generated by Django 3.1.6 on 2021-04-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('buy_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_subject', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=200)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Supervisor'), (3, 'User')], default=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'InActive'), (3, 'Rejected')], default=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
