# Generated by Django 3.0.8 on 2021-04-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
