# Generated by Django 3.0.8 on 2021-04-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_sell_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
