# Generated by Django 3.1.6 on 2021-06-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20210610_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.CharField(max_length=200)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
