# Generated by Django 3.1.6 on 2021-06-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyor',
            name='area',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='division',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='graduation_subject',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='sub_district',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='university',
        ),
    ]
