# Generated by Django 3.1.6 on 2021-06-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_auto_20210610_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')], default=2, null=True),
        ),
    ]
