# Generated by Django 3.1.6 on 2021-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0008_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
